#!/usr/bin/env python3
"""Generate Sources/GPUMetricsLayout.swift from upstream kgd_pp_interface.h.

The offsets come from the C compiler, not from hand-counting: this script
extracts struct metrics_table_header and the discrete-GPU gpu_metrics_v1_*
structs (plus the types and constants they use) from the header, compiles a
program that prints offsetof/sizeof of every field the monitor reads, and
writes the Swift table that the decoder selects by the blob's header
(format_revision, content_revision).

Usage: gen_gpu_metrics.py [PATH/TO/kgd_pp_interface.h]
  (default: third_party/kgd_pp_interface.h, vendored from upstream Linux;
   pass another copy of the header to regenerate against it)
"""
import hashlib
import re
import subprocess
import sys
import tempfile
from pathlib import Path

FIELDS = [
    "temperature_edge", "temperature_hotspot", "temperature_mem",
    "temperature_vrgfx", "temperature_vrsoc", "temperature_vrmem",
    "average_gfx_activity", "average_umc_activity", "average_mm_activity",
    "average_socket_power", "curr_socket_power",
    "average_gfxclk_frequency", "average_socclk_frequency", "average_uclk_frequency",
    "average_vclk0_frequency", "average_dclk0_frequency",
    "current_gfxclk", "current_socclk", "current_uclk", "current_vclk0", "current_dclk0",
    "throttle_status", "indep_throttle_status", "current_fan_speed",
    "pcie_link_width", "pcie_link_speed",
    "voltage_soc", "voltage_gfx", "voltage_mem",
    "energy_accumulator", "system_clock_counter", "firmware_timestamp",
]
# gpu_metrics_v1_9 is the attribute-encoded format (pointers); v2/v3 are APU
# layouts with different units. Neither has a fixed dGPU field layout.
FORMATS = [(1, c) for c in range(9)]


def struct_block(text, name):
    match = re.search(r"^struct %s \{.*?^\};" % re.escape(name), text, re.S | re.M)
    if not match:
        raise SystemExit(f"struct {name} not found")
    return match.group(0)


def main():
    if len(sys.argv) > 2 or (len(sys.argv) == 2 and sys.argv[1] in ("-h", "--help")):
        raise SystemExit(__doc__)
    if len(sys.argv) == 2:
        header = Path(sys.argv[1])
    else:
        header = Path(__file__).resolve().parent / "third_party" / "kgd_pp_interface.h"
    text = header.read_text()
    digest = hashlib.sha256(text.encode()).hexdigest()[:12]
    defines = re.findall(r"^#define\s+(?:NUM|MAX)_\w+\s+\d+\s*$", text, re.M)
    blocks = [struct_block(text, "metrics_table_header")]
    for name in re.findall(r"^struct (amdgpu_xcp_metrics\w*) \{", text, re.M):
        blocks.append(struct_block(text, name))
    present = {}
    for frev, crev in FORMATS:
        name = f"gpu_metrics_v{frev}_{crev}"
        block = struct_block(text, name)
        blocks.append(block)
        fields = {}
        for kind, field, count in re.findall(r"\b(u?int\d+_t)\s+(\w+)\s*(?:\[(\w+)\])?\s*;", block):
            if field in FIELDS:
                fields[field] = count
        present[(frev, crev)] = fields
    program = ["#include <stddef.h>", "#include <stdint.h>", "#include <stdio.h>", *defines, *blocks,
               "int main(void) {"]
    for (frev, crev), fields in present.items():
        name = f"gpu_metrics_v{frev}_{crev}"
        program.append(f'    printf("F {frev} {crev} %zu\\n", sizeof(struct {name}));')
        for field, count in fields.items():
            element = f"((struct {name} *)0)->{field}" + ("[0]" if count else "")
            whole = f"((struct {name} *)0)->{field}"
            program.append(f'    printf("f {field} %zu %zu %zu\\n", offsetof(struct {name}, {field}), '
                           f"sizeof({element}), sizeof({whole}) / sizeof({element}));")
    program.append("    return 0;\n}\n")
    with tempfile.TemporaryDirectory() as work:
        source = Path(work, "layout.c")
        binary = Path(work, "layout")
        source.write_text("\n".join(program))
        subprocess.run(["clang", "-std=c11", "-o", str(binary), str(source)], check=True)
        output = subprocess.run([str(binary)], check=True, capture_output=True, text=True).stdout
    lines = [
        "// Generated by gen_gpu_metrics.py from kgd_pp_interface.h "
        f"(sha256 {digest}); do not edit.",
        "// Byte layout of the discrete-GPU gpu_metrics formats, selected by the",
        "// blob's metrics_table_header, never by ASIC. Offsets are the C compiler's.",
        "",
        "struct GPUMetricsField {",
        "    let offset: Int",
        "    let size: Int     // bytes per element",
        "    let count: Int    // elements (arrays: one per instance)",
        "}",
        "",
        "struct GPUMetricsFormat {",
        "    let formatRevision: UInt8",
        "    let contentRevision: UInt8",
        "    let size: Int",
        "    let fields: [String: GPUMetricsField]",
        "}",
        "",
        "enum GPUMetricsLayout {",
        "    static let formats: [GPUMetricsFormat] = [",
    ]
    current = None
    for line in output.splitlines():
        parts = line.split()
        if parts[0] == "F":
            if current:
                lines.append("        ]),")
            current = parts
            lines.append(f"        GPUMetricsFormat(formatRevision: {parts[1]}, contentRevision: {parts[2]}, "
                         f"size: {parts[3]}, fields: [")
        else:
            _, field, offset, size, count = parts
            lines.append(f'            "{field}": GPUMetricsField(offset: {offset}, size: {size}, count: {count}),')
    lines.append("        ]),")
    lines.append("    ]")
    lines.append("}")
    out = Path(__file__).resolve().parent / "Sources" / "GPUMetricsLayout.swift"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
